service: static-site-mailer

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource: ["*"]
  apiGateway:
    shouldStartNameWithService:
      true


functions:
  staticSiteMailer:
    handler: handler.staticSiteMailer
    events:
      - http:
          method: post
          path: static-site-mailer
          cors: true